sudo: required

services:
  - docker

env:
  global:
    - HKEYDIR=/tmp/dnscrypt-wrapper/keys # Directory for keys on host
    - CKEYDIR=/opt/dnscrypt-wrapper/etc/keys # Directory for keys in container

install:
  - docker build -t dnscrypt-wrapper .
  - rm -rf $HKEYDIR
  - mkdir -p $HKEYDIR
  # TODO: Start local DNS server, to avoid dependence on the external one at 8.8.8.8

script:
  # Generate keys
  - docker run --interactive --tty --rm dnscrypt-wrapper --version
  - 'docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper --gen-provider-keypair | tee /tmp/gen-provider-keypair.log'
  - 'PUBLIC_KEYPAIR_FINGERPRINT=$(egrep ''Public key fingerprint: '' /tmp/gen-provider-keypair.log | sed ''s/Public key fingerprint: //''); echo $PUBLIC_KEYPAIR_FINGERPRINT | tee $HKEYDIR/fingerprint; [ ! -z "$PUBLIC_KEYPAIR_FINGERPRINT" ]'
  - stat -t $HKEYDIR/public.key
  - stat -t $HKEYDIR/secret.key
  - docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper --gen-crypt-keypair
  - stat -t $HKEYDIR/crypt_secret.key
  - docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper --gen-cert-file
  - stat -t $HKEYDIR/dnscrypt.cert
  # start wrapper
  - 'docker run --volume=$HKEYDIR:$CKEYDIR --expose=443 --name=wrapper --detach \
       -e LISTEN_ADDRESS=0.0.0.0
       -e LISTEN_PORT=443
       -e PROVIDER_NAME=2.dnscrypt-cert.test.dnscrypt.io
       dnscrypt-wrapper \
  # Is the dnscrypt-wrapper container running? And what did it do?
  - sleep 10; docker ps | grep dnscrypt-wrapper; docker logs --details -t wrapper
  # Get wrapper internal ip
  - 'WRAPPERIP=$(docker inspect -f ''{{ .NetworkSettings.IPAddress }}'' wrapper)'
  - echo $WRAPPERIP
  # Run dnscrypt proxy
  - docker run -e RESOLVER_ADDR=$WRAPPERIP:443 -e PROVIDER_NAME=2.dnscrypt-cert.test.dnscrypt.io -e PROVIDER_KEY=$PUBLIC_KEYPAIR_FINGERPRINT -e LOGLEVEL=7 -p 127.0.0.1:53:53/udp dnscryptio/dnscrypt-proxy-docker
  - dig @127.0.0.1 www.google.com
