sudo: required

services:
  - docker

install:
  - mkdir -p /tmp/dnscrypt-wrapper/keys
  - KEYDIR=/tmp/dnscrypt-wrapper/keys
  - CONKEYDIR=/opt/dnscrypt-wrapper/etc/keys
  - docker build -t dnscrypt-wrapper-docker .
  - bash -c 'docker run --interactive --tty --rm --volume $KEYDIR:$CONKEYDIR -w $CONKEYDIR dnscrypt-wrapper-docker --gen-provider-keypair \| tee /tmp/gen-provider-keypair.log'
  - bash -c 'egrep \"Public key fingerprint: \" /tmp/gen-provider-keypair.log \| sed \"s/Public key fingerprint: //\" >> /tmp/public_keypair-fingerprint'
  - cat /tmp/public_keypair-fingerprint
  - docker run --interactive --tty --rm --volume $KEYDIR:$CONKEYDIR -w $CONKEYDIR dnscrypt-wrapper-docker --gen-crypt-keypair
  - docker run --interactive --tty --rm --volume $KEYDIR:$CONKEYDIR -w $CONKEYDIR dnscrypt-wrapper-docker --gen-cert-file
  - docker run --interactive --tty --rm --volume $KEYDIR:$CONKEYDIR -w $CONKEYDIR dnscrypt-wrapper-docker --show-provider-publickey-fingerprint --provider-publickey-file=public.key

before_script:
  - docker pull dnscryptio/dnscrypt-proxy-docker
  - docker run -d -p 127.0.0.1:53:53/udp dnscryptio/dnscrypt-proxy-docker

script:
  - docker run -d -v $KEYDIR:$CONKEYDIR -p 127.0.0.1:4443:4443/udp dnscrypt-wrapper-docker --listen-address=0.0.0.0:4443 --resolver-address=8.8.8.8:53 --provider-name=2.dnscrypt-cert.test.dnscrypt.io --provider-cert-file=/opt/dnscrypt-wrapper/etc/keys/dnscrypt.cert --crypt-secretkey-file=/opt/dnscrypt-wrapper/etc/keys/crypt_secret.key
  - dig @127.0.0.1 google.com
  - dig @127.0.0.1 dnscrypt.org
